name: Check PR Title

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  check-title:
    name: Validate PR Title
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Validate PR Title
        run: |
          if ! echo "${{ github.event.pull_request.title }}" | grep -E "^(feat|fix|docs|style|refactor|test|chore|perf|build|ci|revert|BREAKING CHANGE)(\(.+\))?: .{1,}$"; then
            echo "❌ Pull request title '${{ github.event.pull_request.title }}' does not follow Conventional Commits."
            exit 1
          else
            echo "✅ Pull request title follows Conventional Commits."
          fi
